// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import starlightBlog from 'starlight-blog';
import starlightLinksValidator from 'starlight-links-validator';

// GitHub Pages project site: served at https://ghchinoy.github.io/mizan/
// `base` MUST be carried by every internal link/asset. sync-docs.mjs emits
// base-prefixed routes and internal assets go through Astro's pipeline so the
// prefix is applied automatically.
export default defineConfig({
  site: 'https://ghchinoy.github.io',
  base: '/mizan',
  integrations: [
    starlight({
      title: 'Mizan',
      social: [
        { icon: 'github', label: 'GitHub', href: 'https://github.com/ghchinoy/mizan' },
      ],
      // Edit links point at the authoritative source in `docs/`, never the
      // generated copy under src/content/docs/. sync-docs.mjs also injects a
      // per-page `editUrl` so generated guides resolve to their real source file.
      editLink: {
        baseUrl: 'https://github.com/ghchinoy/mizan/edit/main/docs/',
      },
      plugins: [
        starlightBlog({
          title: 'Blog',
          authors: {
            ghchinoy: {
              name: 'ghchinoy',
              title: 'Mizan maintainer',
              url: 'https://github.com/ghchinoy',
            },
          },
        }),
        // Broken internal links and invalid heading anchors fail `npm run build`.
        // Defaults: errorOnRelativeLinks/errorOnInvalidHashes/failOnError = true;
        // external links are ignored.
        //
        // `exclude` (Phase 3, narrowed from the Phase 1 workaround):
        // Only the blog *index* route (`/mizan/blog/`) is excluded. It is a
        // starlight-blog *injected* route with no markdown source, so the
        // validator cannot see it as a valid link target and would flag every
        // link to it. Everything ELSE under /mizan/blog/ is now validated:
        //   - individual posts (/mizan/blog/<slug>/) ARE markdown-sourced, so a
        //     broken link to a post now correctly fails the build;
        //   - injected tag/author routes and /mizan/blog/rss.xml are not linked
        //     from our markdown, so they need no exclusion.
        // The Phase 1 `'/mizan/blog/**'` glob is intentionally REMOVED so that
        // genuine broken links to/among blog posts are caught. (Verified: with
        // no exclusion, ONLY `/mizan/blog/` is reported invalid.)
        starlightLinksValidator({
          exclude: ['/mizan/blog', '/mizan/blog/'],
        }),
      ],
      sidebar: [
        // The Build Evals series reading order (seriesOrder), complementing the
        // date-ordered Blog link that starlight-blog injects.
        { label: 'Build Evals series', link: '/blog-series/' },
        { label: 'Guides', items: [{ autogenerate: { directory: 'guides' } }] },
        // Reference & Design docs (architecture, collaboration, research,
        // implementation-plan, spikes, RFCs) — autogenerated from the generated
        // `reference` tree that sync-docs.mjs produces from docs/.
        { label: 'Reference & Design', items: [{ autogenerate: { directory: 'reference' } }] },
        // The Blog top-level link is injected by starlight-blog.
      ],
      // Override MarkdownContent to add the "Series" banner on blog posts while
      // delegating all blog rendering to starlight-blog's own override.
      components: {
        MarkdownContent: './src/components/MarkdownContent.astro',
      },
    }),
  ],
});
